import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ProductsProvider } from "./context/CartContext";
import { AuthContextProvider } from "./context/AuthContext";
import { ContactProvider } from "./context/MyContactContext";
import { SendingToProvider } from "./context/SendingToContext";
import { DeliveryMethodProvider } from "./context/DeliveryMethodContext";
import { IdentificationProvider } from "./context/IdentificationContext";
import { PaymentMethodProvider } from "./context/PaymentMethodContext";
import { CartModalProvider } from "./context/CartModalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartModalProvider>
        <PaymentMethodProvider>
        <IdentificationProvider>
        <DeliveryMethodProvider>
        <SendingToProvider>
        <ContactProvider>
        <AuthContextProvider>
        <ProductsProvider>
        
        {children}
        </ProductsProvider>
        </AuthContextProvider>
        </ContactProvider>
        </SendingToProvider>
        </DeliveryMethodProvider>
        </IdentificationProvider>
        </PaymentMethodProvider>
        </CartModalProvider>
        </body>
        
    </html>
  );
}
